from django.urls import path
from . import views

app_name = 'comps'

urlpatterns = [
    path('', views.HomeView.as_view(), name = 'home'),
    path('worker/add', views.CreateWorker.as_view(), name = 'add_worker'),
    path('worker/list', views.ListWorker.as_view(), name = 'list_worker'),
    path('worker/edit/<pk>', views.UpdateWorker.as_view(), name = 'edit_worker'),
    path('worker/toggle/<pk>', views.ToggleWorker.as_view(), name = 'toggle_worker'),
    path('worker/delete/<pk>', views.DeleteWorker.as_view(), name = 'delete_worker'),
    path('crop/add', views.CreateCrop.as_view(), name = 'add_crop'),
    path('crop/list', views.ListCrop.as_view(), name = 'list_crop'),
    path('crop/edit/<pk>', views.UpdateCrop.as_view(), name = 'edit_crop'),
    path('crop/toggle/<pk>', views.ToggleCrop.as_view(), name = 'toggle_crop'),
    path('crop/delete/<pk>', views.DeleteCrop.as_view(), name = 'delete_crop'),
    path('equipment/add', views.CreateEquipment.as_view(), name = 'add_equipment'),
    path('equipment/list', views.ListEquipment.as_view(), name = 'list_equipment'),
    path('equipment/edit/<pk>', views.UpdateEquipment.as_view(), name = 'edit_equipment'),
    path('equipment/toggle/<pk>', views.ToggleEquipment.as_view(), name = 'toggle_equipment'),
    path('equipment/delete/<pk>', views.DeleteEquipment.as_view(), name = 'delete_equipment'),
    path('fertilizer/add', views.CreateFertilizer.as_view(), name = 'add_fertilizer'),
    path('fertilizer/list', views.ListFertilizer.as_view(), name = 'list_fertilizer'),
    path('fertilizer/edit/<pk>', views.UpdateFertilizer.as_view(), name = 'edit_fertilizer'),
    path('fertilizer/toggle/<pk>', views.ToggleFertilizer.as_view(), name = 'toggle_fertilizer'),
    path('fertilizer/delete/<pk>', views.DeleteFertilizer.as_view(), name = 'delete_fertilizer'),
    path('insecticide/add', views.CreateInsecticide.as_view(), name = 'add_insecticide'),
    path('insecticide/list', views.ListInsecticide.as_view(), name = 'list_insecticide'),
    path('insecticide/edit/<pk>', views.UpdateInsecticide.as_view(), name = 'edit_insecticide'),
    path('insecticide/toggle/<pk>', views.ToggleInsecticide.as_view(), name = 'toggle_insecticide'),
    path('insecticide/delete/<pk>', views.DeleteInsecticide.as_view(), name = 'delete_insecticide'),
    path('pesticide/add', views.CreatePesticide.as_view(), name = 'add_pesticide'),
    path('pesticide/list', views.ListPesticide.as_view(), name = 'list_pesticide'),
    path('pesticide/edit/<pk>', views.UpdatePesticide.as_view(), name = 'edit_pesticide'),
    path('pesticide/toggle/<pk>', views.TogglePesticide.as_view(), name = 'toggle_pesticide'),
    path('pesticide/delete/<pk>', views.DeletePesticide.as_view(), name = 'delete_pesticide'),
    path('loan/add', views.CreateLoan.as_view(), name = 'add_loan'),
    path('loan/list', views.ListLoan.as_view(), name = 'list_loan'),
    path('loan/edit/<pk>', views.UpdateLoan.as_view(), name = 'edit_loan'),
    path('loan/delete/<pk>', views.DeleteLoan.as_view(), name = 'delete_loan'),
    path('sales/add', views.CreateSale.as_view(), name = 'add_sale'),
    path('sales/list', views.ListSale.as_view(), name = 'list_sale'),
    path('sales/edit/<pk>', views.UpdateSale.as_view(), name = 'edit_sale'),
    path('profit/add', views.ProfitView.as_view(), name = 'gen_profit'),
    path('profit/list', views.ProfitList.as_view(), name = 'profit_list'),
    path('profit/delete/<pk>', views.DeleteProf.as_view(), name = 'delete_prof'),
]